collections:
  experience:
    output: true
    permalink: /experience/:path/
  education:
    output: true
    permalink: /education/:path/
  projects:
    output: true
    permalink: /projects/:path/


