title: Abdoullatuf Maoulida
logo: /assets/img/img_cv_abdoullatuf.jpg
description: Data Scientist | Ingénieur en IA Recherche d'alternance
theme: jekyll-theme-minimal
include:
  - google_analytics.html

