collections:
  experience:
    output: true
    permalink: /experience/:_experience/experiences.md/
  education:
    output: true
    permalink: /education/:_formation/formations.md/
  projects:
    output: true
    permalink: /projects/:_projet/projets.md/


